### ISSUE TITLE
This cookbook on Supermarket.io?

### ISSUE THREAD

**Issue by yshoaib** [dynaTrace/Dynatrace-Chef#1]
[Chef Supermarket](https://supermarket.chef.io/) is quite useful as a repository to search for and explore cookbooks. Can this cookbook also be included in Supermarket?

**Comment by metmajer** [comment]
Of course! However, we want to make sure that a subset of our customers can successfully use it before we make it public to a larger audience. Will keep you posted here.

**Comment by metmajer** [comment]
Depends on #8.

**Comment by nicka** [comment]
Awesome news!!!

**Comment by metmajer** [comment]
With the public download links being available, we have pushed the Chef cookbook to the Supermarket: https://supermarket.chef.io/cookbooks/dynatrace!
