### ISSUE TITLE
error when starting dtwsagent

### ISSUE THREAD

**Issue by yshoaib** [dynaTrace/Dynatrace-Chef#10]
Error when starting dtwsagent
```
$ sudo service dynaTraceWebServerAgent start

OUTPUT:
File not found or not executable: /opt/dynatrace-6.2-agent/dynatrace/agent/lib/dtwsagent
```

**Comment by metmajer** [comment]
Can you provide your overrides and a view into your filesystem at '/opt/dynatrace-6.2-agent'? Does it work when you don't change the prefix and leave it as '/opt'?

**Comment by metmajer** [comment]
I ran a quick test using Test Kitchen (described in `README.md`).
As`node['dynatrace']['wsagent_package']['linux']['installer']['prefix_dir']` I used `/opt/dynatrace-6.2-agent`:

```
kitchen converge wsagent-package-debian
kitchen login wsagent-package-debian
```

Inside the Docker container, an `ls -l /opt/dynatrace-6.2-agent` shows me:

```
lrwxrwxrwx 1 root      root        38 Aug 18 18:29 dynatrace -> /opt/dynatrace-6.2-agent/dynatrace-6.2
drwxr-xr-x 5 dynatrace dynatrace 4096 Aug 18 18:29 dynatrace-6.2
```

...and a `service dynaTraceWebServerAgent status` shows:

```
dynaTrace WebServer Agent daemon is running:
999       6284     1  0 18:44 ?        00:00:01 /opt/dynatrace-6.2-agent/dynatrace/agent/lib64/dtwsagent
```

Not sure where things break on your end, but I am curious to learn.

**Comment by metmajer** [comment]
Can I close the issue?

**Comment by yshoaib** [comment]
I am very sorry @metmajer I haven't yet had a chance to look into this. Will check as soon as I get a chance. Will keep you posted.
