### ISSUE TITLE
Agent package and WsAgent are competing when installed to the same directory 

### ISSUE THREAD

**Issue by metmajer** [Dynatrace/Dynatrace-Chef#12]
`agents_package` and `wsagent_package` both share the `agent` directory when installed to the same directory. Whoever is installed last will effectively overwrite the installation of the former.

Proposed solution as of now: when both agents are required on the same host, install them into different directories, using the respective `...['installer']['prefix_dir']` attributes.

**Comment by pozieblo** [comment]
Fixed by allowing to install different Dynatrace packages in the same directory (e.g. /opt/dynatrace) - replaced mv command by rsync.
