### ISSUE TITLE
piping bitness/Y/Y via echo is not really necessary anymore

### ISSUE THREAD

**Issue by Dynatrace-Reinhard-Pilz** [Dynatrace/Dynatrace-Chef#15]
Just as a hint - the installers since dynaTrace 6.1 are able to get parameterized with the arguments -b/-bitness and -y/-yes and are therefore truly non interactive.
Therefore the trick with piping in additional input via echo -e is actually not required anymore.

**Comment by metmajer** [comment]
Thanks @Dynatrace-Reinhard-Pilz! Will account for this in one of the next releases.
