### ISSUE TITLE
Agent can only be injected once per host

### ISSUE THREAD

**Issue by metmajer** [Dynatrace/Dynatrace-Chef#18]
The current implementation uses a Chef recipe to install, e.g., [a Java agent](https://github.com/Dynatrace/Dynatrace-Chef/blob/master/recipes/java_agent.rb). The recipe has to be turned into an [LWRP](https://docs.chef.io/custom_resources.html), as a recipe can only be applied once (whereas LWRPs can be applied multiple times).

Examples or LWRPs in this project can be found here:

- https://github.com/Dynatrace/Dynatrace-Chef/tree/master/resources
- https://github.com/Dynatrace/Dynatrace-Chef/tree/master/providers

**Comment by pozieblo** [comment]
Fixed by creating a dynatrace_java_agent LWRP resource (see resources/java_agent.rb).
