### ISSUE TITLE
Test-kitchen and docker

### ISSUE THREAD

**Issue by yshoaib** [dynaTrace/Dynatrace-Chef#2]
Currently, vagrant is used as a driver in test-kitchen. For testing purposes, it would be efficient to use docker as the driver, which would significantly reduce provisioning times.

**Comment by metmajer** [comment]
@yshoaib Testing inside Docker containers has been made available in `.kitchen.docker.yml` with [v0.1.4](https://github.com/dynaTrace/Dynatrace-Chef/releases/tag/v0.1.4). However, this is still experimental as testing the availability of ports with Serverspec does not work when running inside Docker (Issue [\#150](https://github.com/portertech/kitchen-docker/issues/150)).

**Comment by metmajer** [comment]
Fixed testing inside Docker containers and made this the default in Commit 6f7cbe.

**Comment by yshoaib** [comment]
Many thanks!
