### ISSUE TITLE
Setting group as dynatrace_owner?

### ISSUE THREAD

**Issue by giglio91** [Dynatrace/Dynatrace-Chef#20]
Hello,
I'm not sure if this was coded intentionally or it is a mistake. Line 89 in recipes/wsagent_package.rb is setting group of dtwsagent.ini as dynatrace_owner.
When I apply the recipe it fails since the owner attribute I override is not recognised as a group on the OS.

Sorry if this has already been discussed and thanks for reply.
Francesco

**Comment by giglio91** [comment]
I'm experiencing a strange behaviour.
If I override only the owner attribute (say I set it to "dtuser") and run the cookbook, I encounter no error. But I found out that the recipe creates two groups, one named "dtuser" and another named "dynatrace" (the default group attribute value).

Instead, if I override both the owner and the group (say I set them to "oracle" and "dba" respectively), the recipe hangs on line 89, saying it cannot find "oracle" group.

Why this is happening? I do not understand both behaviours.

Many thanks.
Francesco

**Comment by metmajer** [comment]
Thanks @giglio91 for filing this issue. We'll have a look at it, stay tuned!

**Comment by pozieblo** [comment]
There was an error while setting the group for the dtwsagent.ini file (see commit270ceea365). Fix committed to master, 6.3 and 6.5 branches.

**Comment by giglio91** [comment]
Thanks a lot @metmajer @pozieblo. I saw you released a lot of features today, I'll try the new cookbook asap. Good work!
