### ISSUE TITLE
allow a toggle on the java recipe include

### ISSUE THREAD

**Issue by jkerry** [Dynatrace/Dynatrace-Chef#23]
It would be nice to allow for a boolean flag to turn on / off the include_recipe on the java cookbook.  We've got a lightweight jdk resource that we prefer to some of the extra content in the java cookbook.

**Comment by pozieblo** [comment]
We will be working on it this week. As a workaround you can try to uncomment `include_recipe 'java'` in `server.rb` and `collector.rb` recipes.

**Comment by pozieblo** [comment]
The fix is available in commit cfa2f2279d6. To not include the java recipe please override the ['dynatrace']['java']['install_jdk'] attribute and set it to false.
