### ISSUE TITLE
Dynatrace java attributes 

### ISSUE THREAD

**Issue by tobymaro** [Dynatrace/Dynatrace-Chef#27]
Hello,

There is attribute:
override['java']['jdk_version'] = '7'

I thinks it's bad idea to set this as "override". I have another services on the same node that installs java 8. But once I added java_agent recipe I get java 1.7 on machine. 

Could you please correct it or explain why you do it? 

Thank You.

**Comment by pozieblo** [comment]
Dynatrace 6.5 packages require Java version 1.7 to unpack the .jar files thus the need for this line (by default the java cookbook installs version 6). 
What we can do is to replace the `override` keyword by `default` which should work just fine in this case and will allow to override this attribute in wrapper cookbooks.

**Comment by tobymaro** [comment]
Hi, 
It's ok to use default.
thanx

**Comment by pozieblo** [comment]
Fix available in commit aa0775c1ae
