### ISSUE TITLE
web server agent won't work in 32 bit architecture 

### ISSUE THREAD

**Issue by cvillalba** [Dynatrace/Dynatrace-Chef#28]
Hi all

We are testing the new version of Dynatrace using this recipe and make it work perfectly in 64 bit architecture, but when attempt to install the agent in a server with 32 bit architecture, apparently it is trying to run the 64 binary file anyways and the daemon won't start.

We already have set the x86 arch attribute and the collector is connected correctly as well.

Can you please let me know if there is an issue with the recipe or we are doing something wrong.
Greetings.

**Comment by pozieblo** [comment]
Actually we are internally using a web server agent injected into a 32 bit Apache Server (but on a 64 bit Linux OS) without any issues. In such case (32 bit web server on a 64 bit machine) a special package has to be installed though - see http://stackoverflow.com/questions/8328250/centos-64-bit-bad-elf-interpreter. 
If this is not your case, could you provide some logs and details about your setup (e.g. OS)? Specifically there may be some useful information in the /opt/dynatrace/log/dt_wsagent* files.

**Comment by cvillalba** [comment]
Hi @pozieblo 

Actually it's not our case, we tried to install de 32 bit agent in a 32 bit arch, but we already found the problem. 

In the attributes of wsagent_package at line 28 there is a fixed default file url targeting the 64 bit version of the agent. 

We will be happy to place a pull request adding the condition based on [kernel][machine] system property to set the correct agent version.

Let me know if you are ok with it.

**Comment by pozieblo** [comment]
Thanks for the help you propose. Before sending a pull request we need to internally discuss this topic i.e. support for 32-bit OS in general. As I understand the simplest workaround for now is to override the `node['dynatrace']['wsagent_package']['linux']['installer']['file_url']` attribute with a 32-bit package, right?

**Comment by cvillalba** [comment]
Exactly, we change the file_url to 32-bit and that's it. That is why I suggest to define de url based on the server architecture.
Let me know if I can help with the change.

**Comment by pozieblo** [comment]
It seems that the proposed workaround is good enough so I am closing this ticket.
