### ISSUE TITLE
how to test performance warehouse?

### ISSUE THREAD

**Issue by yshoaib** [dynaTrace/Dynatrace-Chef#4]
Probably a documentation on how to test performance warehouse may be useful.

**Comment by metmajer** [comment]
@yshoaib testing the connectivity between the Dynatrace server and the performance warehouse database has been properly integrated into [v0.1.4](https://github.com/dynaTrace/Dynatrace-Chef/releases/tag/v0.1.4). Please refer to the release's Changelog documentation and from there take a look at the changeset that handles the integration.
