### ISSUE TITLE
jvm parameters in the .ini files

### ISSUE THREAD

**Issue by yshoaib** [dynaTrace/Dynatrace-Chef#5]
There is currently no way to set the jvm memory parameter values of the .ini configuration files.

**Comment by metmajer** [comment]
Resolved for the Dynatrace Collector by Commit ab7663d,

**Comment by yshoaib** [comment]
Thanks @metmajer 

There are two settings for the server as well: MaxPermSize and PermSize, which are not yet externalized through the attributes.

**Comment by metmajer** [comment]
@yshoaib all server memory settings are handled via the sizings in the server settings (ref. t-shirt sizes demo, S, M, ...) and should only be altered in this context
