### ISSUE TITLE
separating licence install from server recipe

### ISSUE THREAD

**Issue by yshoaib** [dynaTrace/Dynatrace-Chef#6]
Currently, the license install is part of the server recipe, please refer [here](https://github.com/dynaTrace/Dynatrace-Chef/blob/master/recipes/server.rb#L79-L97)

Is it possible to separate this latter part into another recipe? This allows for testing server installation separately before license installation.

**Comment by metmajer** [comment]
@yshoaib Could you explain which part of the server installation testing you are referring to? Problem is that the server test suite in `test/integration/servespec/server` runs an integration test that verifies the proper connectivity between the server and a performance warehouse. Currently, setting this configuration at the server requires a license to be installed.

**Comment by metmajer** [comment]
The necessity to have a license in place was a bad idea anyway. I have separated the license installation from the server installation and have gotten rid of the license dependency in testing in Commit 028e33c.
