### ISSUE TITLE
Integrate public download links for all Dynatrace installers

### ISSUE THREAD

**Issue by metmajer** [dynaTrace/Dynatrace-Chef#8]
Public download links for Dynatrace installers will soon be made available. Integrate these links so that a respective installer will be downloaded if it has not already been made available in the cookbook's `files` directory.

**Comment by nicka** [comment]
Just noticed the new cookbook version! I'm so glad you added the public download links. This makes it much easier to get started using the Dynatrace software. Another plus, it removed about 1.5GB from our repository(I know, bad idea to keep the downloads in a repo).

Will definitely start using the latest cookbook and update you on any issues.

**Comment by metmajer** [comment]
@nicka Happy to read that you like our recent integrations. All installers can now be obtained from via http://downloads.dynatracesaas.com/.
