### ISSUE TITLE
Missing execute mode for init scripts

### ISSUE THREAD

**Issue by yshoaib** [dynaTrace/Dynatrace-Chef#9]
The init scripts are missing executable permissions [here](https://github.com/dynaTrace/Dynatrace-Chef/blob/master/providers/configure_init_scripts.rb#L25). The causes the script to not start.

**Comment by metmajer** [comment]
Hmm. Maybe we should make it 0755, but then have it owned by root:root. Your opinion?

**Comment by metmajer** [comment]
Totally makes sense. Resolved in d4bcc04.

**Comment by yshoaib** [comment]
thank you @metmajer for the quick resolution. amazing :+1:
